version: '3.8'
services:
    nginx:
        container_name: 'server'
        build:
            context: "./docker/nginx"
        depends_on:
            - app
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            - sail
    app:
        container_name: 'rolebase'
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
        ports:
            - '8081:80'
            - '5173:5173'
        volumes:
            - './:/var/www/html/app'
        depends_on:
            - mariadb
        networks:
            - sail
        expose:
            - "9000"

    mariadb:
        container_name: 'db'
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/mariadb:/var/lib/mysql'
        networks:
            - sail
    redis:
        container_name: 'cache'
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - './docker/redis:/data'
        networks:
            - sail
networks:
    sail:
        driver: bridge
